### ISSUE TITLE
API endpoints are not secured.

### ISSUE THREAD

**Issue by ghost** [Dex1019/Veggkart#5]
Anybody with [this link](http://nullsquad.in/api/upload_1.php) (from your source code) can place orders. A couple of the ways you can prevent it :
1. Add provision of a basic login-password authentication to your API.
2. **DO NOT** version control (or hard-code) your API's endpoints or credentials.

**Comment by coder09** [comment]
thanks @dhruvin2910 , for your feedback. yes, it's an useful insight and matter of fact, it did cross through my mind. Honestly, I didn't knew what to do to mitigate this security issue. Then again for the business model -we are working for- is tolerant to this kind of problem, and that’s the reason I left it as such. To assure you, 
1. This is not the actual link that will be used for production version. These are just for testing.
2. I have secured the server-side script code. for my eyes only.
3. I'll work on it. lots of learning(LOL) to do
